### ISSUE TITLE
3 islands are uncolonizable due to both being a Trade Post and not being in any expedition group

### ISSUE THREAD

**Issue by MichaHelder** [MEIOU-and-Taxes/MEIOUandTaxes#14]
Report from goik on the community server: 

> Ascension(2520), St Helena(1098) and Ilois(1101) can't be colonized due to being a trade post, but aren't part of any expedition target making it impossible to colonize

Edit: something isn't working properly with uploading a screenshot here. Original message can be found in the bug-reports channel, posted on 12th of August 2023 11:37PM CEST

Will assign the issue to myself for now

**Comment by Jarkami** [comment]
Fixed by https://github.com/MEIOU-and-Taxes/MEIOUandTaxes/commit/948524bbe92470bd01aaab29ebd14573b3e8488e
